### ISSUE TITLE
Unable to build the project with the mvnw command

### ISSUE THREAD

**Issue by LevesqueJ99** [smoketurner/dropwizard-graphql#13]
As soon as I tried to build the project with the command  ./mvnw clean package I get the error
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project graphql-core: Fatal error compiling: Error while executing the compiler. InvocationTargetException: ANNOTATION_PROCESSOR_MODULE_PATH -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :graphql-core

Not sure what to do as I haven't changed any configurations to your project.

**Comment by jplock** [comment]
@LevesqueJ99 sorry about that.  I removed error_prone and nullaway which were causing issues on later JDK's.  It should compile now on JDK9+ (the artifacts are still targeted to JDK8).

**Comment by LevesqueJ99** [comment]
The project build without any problems now. 

Thank you for your help 👍.
