### ISSUE TITLE
GraphQLBundle having another override `getGraphQLSchema()`?

### ISSUE THREAD

**Issue by tberman** [smoketurner/dropwizard-graphql#14]
I am building the schema via manual objects instead of via the RuntimeWiring and SDL files. However, the GraphQLFactory abstraction that is currently exposed in this plugin requires you to be using RuntimeWiring.

If I put together a PR that added a `getGraphQLSchema()` overridable function that can optionally be used instead would that be accepted?

**Comment by jplock** [comment]
@tberman sure, as long as its backward compatible, that sounds great.

**Comment by kito99** [comment]
I had the same issue -- I'm using graphql-java-tools. I had to create my own `CustomGraphQLFactory` that basically copied the code for the `build()` method and created the schema using graphql-java-tools' `SchemaParser`. Having this as a method that can be easily overridden would be nice.

**Comment by jplock** [comment]
I'd be happy to review a PR for this.

**Comment by rcleps** [comment]
How do you guys solve this? I just add a GraphQLSchema property to the factory, so we can create the schema external of the GraphQLBundle and set in the initialize of the project.

**Comment by jplock** [comment]
Just published `1.3.12-1` with this fix to Maven Central.  Thanks!
