### ISSUE TITLE
dependency convergence issue

### ISSUE THREAD

**Issue by ChitturiPadma** [smoketurner/dropwizard-graphql#15]
When trying to do mvn clean install, compilation of  Dropwizard GraphQL Bundle fails and this is the error/warning i see -
Dependency convergence error for org.assertj:assertj-core:3.11.1 paths to dependency are:
+-com.smoketurner.dropwizard:graphql-core:1.3.8-2-SNAPSHOT
  +-org.assertj:assertj-core:3.11.1
and
+-com.smoketurner.dropwizard:graphql-core:1.3.8-2-SNAPSHOT
  +-io.dropwizard:dropwizard-testing:1.3.8
    +-org.assertj:assertj-core:3.9.1

**Comment by jplock** [comment]
That's just a test dependency, so it should be ok.
