### ISSUE TITLE
Facing issue when building Dropwizard GraphQL Bundle

### ISSUE THREAD

**Issue by ChitturiPadma** [smoketurner/dropwizard-graphql#16]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project graphql-core: Fatal error compiling: invalid flag: --release -> [Help 1]

What does this actually indicate ?

**Comment by jplock** [comment]
What command are you running to generate that error?
