### ISSUE TITLE
Apollo GraphQL Federation

### ISSUE THREAD

**Issue by brycejlowe** [smoketurner/dropwizard-graphql#80]
Hi,

Recently I forked this project to support a Dropwizard application's integration with Apollo Gateway.  I was curious if you are interested in having this code merged back.  I'm more than willing to make any adjustments to my copy in order to have the contribution be accepted as I hope it might be useful to other Dropwizard users.

Let me know if this is of any interest.

Thanks,
Bryce

**Comment by jplock** [comment]
@brycejlowe if the changes are backward compatible I’d be interested in merging

**Comment by brycejlowe** [comment]
@jplock I'll work on making the changes backwards compatible.  I ran into an issue with the older version of the graphql-java-servlet and I had to bump the version.  I'll hopefully have a PR in a couple of days.

**Comment by brycejlowe** [comment]
@jplock I've got a draft PR open to add the functionality.  I'm going to work through putting some examples together on how it all works as well.  Feel free to let me know if you would like changes
